[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyBe2sIpXy2AHwUFXbjR4lumBA0OlgeG-eM"
  VITE_FIREBASE_AUTH_DOMAIN = "kahal-shelanu-prod.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "kahal-shelanu-prod"
  VITE_FIREBASE_STORAGE_BUCKET = "kahal-shelanu-prod.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "304157811698"
  VITE_FIREBASE_APP_ID = "1:304157811698:web:31aaae5ca9c9ce4f33416b"
